version: {build}
configuration: Release
skip_non_tags: true
platform: x86
before_build:
- cmd: Update-AppveyorBuild -Version "%APPVEYOR_REPO_TAG_NAME%-%APPVEYOR_BUILD_VERSION%"
build:
  verbosity: minimal
after_build:
- cmd: 7z a sb_output_controller_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\SBOutputController\bin\x86\Release\*
artifacts:
- path: sb_output_controller_%APPVEYOR_BUILD_VERSION%.zip
  name: sb_output_controller
deploy:
- provider: GitHub
  auth_token:
    secure: Wl8JicOIG/RIyruxyHhi3ZENowMCOlWhuxzjPSoiEegFJbxyvQAvAevpAYOIqsxI
  artifact: sb_output_controller
  on:
    branch: main
