version: 1.0.{build}
configuration: Release
platform: x86
build:
  verbosity: minimal
after_build:
- cmd: 7z a sb_output_controller_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\SBOutputController\bin\x86\Release\*
artifacts:
- path: sb_output_controller_%APPVEYOR_BUILD_VERSION%.zip
  name: sb_output_controller
deploy:
- provider: GitHub
  auth_token:
    secure: Wl8JicOIG/RIyruxyHhi3ZENowMCOlWhuxzjPSoiEegFJbxyvQAvAevpAYOIqsxI
  artifact: sb_output_controller
  on:
    branch: main
