version: build-{build}
configuration: Release
skip_non_tags: true
platform: x86
before_build:
- cmd: echo %APPVEYOR_REPO_TAG_NAME% > SBOutputController\version.txt
build:
  verbosity: minimal
after_build:
- cmd: 7z a sb_output_controller_%APPVEYOR_REPO_TAG_NAME%.zip %APPVEYOR_BUILD_FOLDER%\SBOutputController\bin\x86\Release\*
artifacts:
- path: sb_output_controller_%APPVEYOR_REPO_TAG_NAME%.zip
  name: sb_output_controller
deploy:
- provider: GitHub
  auth_token:
    secure: Wl8JicOIG/RIyruxyHhi3ZENowMCOlWhuxzjPSoiEegFJbxyvQAvAevpAYOIqsxI
  artifact: sb_output_controller
  on:
    branch: main
