//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOutputController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Creative\\Sound Blaster Command\\Creative.SBCommand.exe")]
        public string SBExecutablePath {
            get {
                return ((string)(this["SBExecutablePath"]));
            }
            set {
                this["SBExecutablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G6")]
        public string LastSelectedDevice {
            get {
                return ((string)(this["LastSelectedDevice"]));
            }
            set {
                this["LastSelectedDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SBOutputController.HotKey HotKeyOutputHeadphones {
            get {
                return ((global::SBOutputController.HotKey)(this["HotKeyOutputHeadphones"]));
            }
            set {
                this["HotKeyOutputHeadphones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SBOutputController.HotKey HotKeyOutputSpeakers {
            get {
                return ((global::SBOutputController.HotKey)(this["HotKeyOutputSpeakers"]));
            }
            set {
                this["HotKeyOutputSpeakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl + Shift + D0")]
        public global::SBOutputController.HotKey HotKeyOutputToggle {
            get {
                return ((global::SBOutputController.HotKey)(this["HotKeyOutputToggle"]));
            }
            set {
                this["HotKeyOutputToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\EqualizerAPO\\config\\headphones.txt")]
        public string EqualizerFilePathHeadphones {
            get {
                return ((string)(this["EqualizerFilePathHeadphones"]));
            }
            set {
                this["EqualizerFilePathHeadphones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\EqualizerAPO\\config\\speakers.txt")]
        public string EqualizerFilePathSpeakers {
            get {
                return ((string)(this["EqualizerFilePathSpeakers"]));
            }
            set {
                this["EqualizerFilePathSpeakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\EqualizerAPO\\config\\config.txt")]
        public string EqualizerFilePathConfig {
            get {
                return ((string)(this["EqualizerFilePathConfig"]));
            }
            set {
                this["EqualizerFilePathConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunOnStartup {
            get {
                return ((bool)(this["RunOnStartup"]));
            }
            set {
                this["RunOnStartup"] = value;
            }
        }
    }
}
